##
#
# Agent <> Planning API
#
# Queries related to planning-level data exposed within an agent context.
#
# @package  vf-graphql
# @since    2020-02-11
#
##

"Query parameters for reading `Commitment`s related to an `Agent`"
input agentCommitmentSearchParams {
  searchString: String
  action: ID
  startDate: DateTime
  endDate: DateTime
  finished: Boolean
}

"Query parameters for reading `Intent`s related to an `Agent`"
input agentIntentSearchParams {
  searchString: String
  action: ID
  startDate: DateTime
  endDate: DateTime
  finished: Boolean
}

interface Agent {
  commitments(filter: agentCommitmentSearchParams): [Commitment!]
  intents(filter: agentIntentSearchParams): [Intent!]
}

type Person implements Agent {
  commitments(filter: agentCommitmentSearchParams): [Commitment!]
  intents(filter: agentIntentSearchParams): [Intent!]
}

type Organization implements Agent {
  commitments(filter: agentCommitmentSearchParams): [Commitment!]
  intents(filter: agentIntentSearchParams): [Intent!]
}
