##
#
# Observation <> Appreciation indexes
#
# Augments EconomicEvent with read-only fields for retrieving reciprocal events.
#
# @package  vf-graphql
# @since    2020-02-12
#
##

type EconomicEvent {
  appreciationOf: [Appreciation!]
  appreciatedBy: [Appreciation!]
}
