##
#
# Planning <> Agreement API
#
# Augments planning records with properties that link events to Agreements
# which have influenced the planning process.
#
# @package  vf-graphql
# @since    2020-02-12
#
##

type Commitment {
  "This commitment is part of the exchange agreement."
  clauseOf: Agreement
}

type Agreement {
  commitments: [Commitment!]
}
