##
#
# Agent module
#
# All functionality related to the definition of autonomous agents
# (people, organizations, groups) and their relationships.
#
#
##

"""
A person or group or organization with economic agency.
"""
interface Agent {
  id: ID!
  name: String!
  # type: String
  image: String
  note: String
  primaryLocation: String
  primaryPhone: String
  email: String

  inventoriedEconomicResources(
    category: EconomicResourceCategory,
    resourceClassificationId: Int,
    page: Int
  ): [EconomicResource]
  searchInventoriedEconomicResources(searchString: String): [EconomicResource]

  processes(finished: Boolean): [Process]
  searchProcesses(searchString: String, finished: Boolean): [Process]

  plans(finished: Boolean, year: Int, month: Int): [Plan]
  searchPlans(searchString: String, finished: Boolean): [Plan]

  economicEvents(action: Action, year: Int, month: Int): [EconomicEvent]

  commitments(action: Action, finished: Boolean): [Commitment]
  searchCommitments(searchString: String, finished: Boolean): [Commitment]

  agentRelationships(roleId: Int, category: AgentRelationshipCategory): [AgentRelationship] #TODO: category
  agentRelationshipsAsSubject(roleId: Int, category: AgentRelationshipCategory): [AgentRelationship] #TODO: category
  agentRelationshipsAsObject(roleId: Int, category: AgentRelationshipCategory): [AgentRelationship] #TODO: category

  roles: [AgentRelationshipRole]

  recipes: [ResourceSpecification] #TODO: is this useful or even realistic?

  # memberRelationships: [AgentRelationship]

  # agentSkills: [ResourceClassification] # can get skills by more generic means... do we want this anyhow?
  # agentSkillRelationships: [AgentResourceClassification] # check this... if keep, rename

  commitmentsMatchingSkills: [Commitment]

  # validatedEventsCount(month: Int, year: Int): Int
  eventsCount(year: Int, month: Int): Int #TODO: ??
  eventHoursCount(year: Int, month: Int): Int #TODO: ??
  eventPeopleCount(year: Int, month: Int): Int #TODO: ??
}

# Variants of agents

"""
A natural person.
"""
type Person implements Agent {
  id: ID!
  name: String!
  # type: String
  image: String
  note: String
  primaryLocation: String
  primaryPhone: String
  email: String

  ### inverse relationships and queries
  inventoriedEconomicResources(
    category: EconomicResourceCategory,
    resourceClassificationId: Int,
    page: Int
  ): [EconomicResource]
  searchInventoriedEconomicResources(searchString: String): [EconomicResource]

  processes(finished: Boolean): [Process]
  searchProcesses(searchString: String, finished: Boolean): [Process]

  plans(finished: Boolean, year: Int, month: Int): [Plan]
  searchPlans(searchString: String, finished: Boolean): [Plan]

  economicEvents(action: Action, year: Int, month: Int): [EconomicEvent]

  commitments(action: Action, finished: Boolean): [Commitment]
  searchCommitments(searchString: String, finished: Boolean): [Commitment]

  agentRelationships(roleId: Int, category: AgentRelationshipCategory): [AgentRelationship] #TODO: category
  agentRelationshipsAsSubject(roleId: Int, category: AgentRelationshipCategory): [AgentRelationship] #TODO: category
  agentRelationshipsAsObject(roleId: Int, category: AgentRelationshipCategory): [AgentRelationship] #TODO: category

  roles: [AgentRelationshipRole]

  recipes: [ResourceSpecification] #TODO: is this useful or even realistic?

  # memberRelationships: [AgentRelationship]
  # agentSkills: [ResourceClassification]
  # agentSkillRelationships: [AgentResourceClassification]

  commitmentsMatchingSkills: [Commitment]

  # validatedEventsCount(month: Int, year: Int): Int
  eventsCount(year: Int, month: Int): Int #TODO: ??
  eventHoursCount(year: Int, month: Int): Int #TODO: ??
}

"""
A formal or informal group, or legal organization.
"""
type Organization implements Agent {
  id: ID!
  name: String
  type: OrganizationClassification #TODO: define how people can create further typing of Organization, also might need a different name
  image: String
  note: String
  primaryLocation: String
  primaryPhone: String
  email: String

  ### inverse relationships and queries
  inventoriedEconomicResources(
    category: EconomicResourceCategory,
    resourceClassificationId: Int,
    page: Int
  ): [EconomicResource]
  searchInventoriedEconomicResources(searchString: String): [EconomicResource]

  processes(finished: Boolean): [Process]
  searchProcesses(searchString: String, finished: Boolean): [Process]

  plans(finished: Boolean, year: Int, month: Int): [Plan]
  searchPlans(searchString: String, finished: Boolean): [Plan]

  economicEvents(action: Action, year: Int, month: Int): [EconomicEvent]

  commitments(action: Action, finished: Boolean): [Commitment]
  searchCommitments(searchString: String, finished: Boolean): [Commitment]

  relationships(roleId: Int, category: AgentRelationshipCategory): [AgentRelationship] #TODO: category
  relationshipsAsSubject(roleId: Int, category: AgentRelationshipCategory): [AgentRelationship] #TODO: category
  relationshipsAsObject(roleId: Int, category: AgentRelationshipCategory): [AgentRelationship] #TODO: category

  roles: [AgentRelationshipRole]

  recipes: [ResourceSpecification] #TODO: is this useful or even realistic?

  # memberRelationships: [AgentRelationship]

  # validatedEventsCount(month: Int, year: Int): Int
  eventsCount(year: Int, month: Int): Int #TODO: ??
  eventHoursCount(year: Int, month: Int): Int #TODO: ??
  eventPeopleCount(year: Int, month: Int): Int #TODO: ??
}

# Relationships between agents

"""
An ongoing voluntary association between 2 agents of any kind.
"""
type AgentRelationship {
  id: ID!
  subject: Agent!
  object: Agent!
  relationship: AgentRelationshipRole!
  note: String
  # probably need the state (and CUD events)
}

"""
A relationship role defining the kind of association one agent can have with another.
"""
type AgentRelationshipRole {
  id: ID!
  label: String!
  inverseLabel: String
  # category: AgentRelationshipCategory #TODO: figure out
}

"""
Generalized behaviors for agent relationship roles
"""
enum AgentRelationshipCategory {  #TODO how do we want to do this concept?
  LEGALPARTNER
  MEMBER
  PART
  PEER
  TRADINGPARTNER
}
