##
#
# Knowledge layer
#
# Provides functionality for classifying and organising other parts of the system.
#
# :TODO: need to figure out a way of making these enums extensible while
#        still validating implementations
#
# @package  HoloREA
# @author   pospi <pospi@spadgos.com>
# @since    2019-02-11
#
##

# Classifications system

"""
Action types define what was 'done' in each `EconomicEvent`.
"""
enum Action {
  NONE
  ACCEPT
  ADJUST
  CITE
  CONSUME
  GIVE
  IMPROVE
  PRODUCE
  TAKE
  USE
  WORK
}

"""
Types of `EconomicResource`s
"""
enum EconomicResourceCategory {
  NONE
  CURRENCY
  INVENTORY
  WORK
}

"""
Classification for declaring types of `Resource`s.
"""
type ResourceClassification {
  id: ID!
  name: String!
  """
  if this resource has different units of use and inventory, this is the unit of inventory
  """
  unit: Unit
  image: String
  note: String
  category: String
  processCategory: String
  classificationResources: [EconomicResource]
}

"""
Types of `Process`es
"""
enum EconomicResourceProcessCategory {
  NONE
  CITED
  CONSUMED
  PRODUCED
  USED
}

"""
Classification for declaring types of `Process`es.
"""
type ProcessClassification {
  id: ID!
  name: String!
  note: String
  scope: Agent
  estimatedDuration: String
}

"""
Associations between different `Agent`s
"""
enum AgentRelationshipCategory {
  NONE
  LEGALPARTNER
  MEMBER
  PART
  PEER
  TRADINGPARTNER
}

"""
Classifies the skill resources that `Agent`s may offer.
"""
type AgentResourceClassification {
  id: ID!
  agent: Agent
  resourceClassification: ResourceClassification
  action: Action
}

"""
Classification for declaring types of `Organisation`s.
"""
type OrganizationClassification {
  id: ID!
  name: String!
  note: String
}

# Facets, for sub-dividing classifications

type Facet {
  id: ID!
  name: String!
  description: String
  facetValues: [FacetValue]
}

type FacetValue {
  id: ID!
  value: String!
  description: String
  facet: [Facet]
}
