##
#
# Observation layer
#
# Records subjective observations as to the state of the material world,
# according to the perspectives of agents. TODO: better definition, not always subjective, can be measured by instruments, etc.
#
# @package  HoloREA
# @since    2019-02-11
#
##

"""
An observed economic flow, as opposed to a flow planned to happen in the future. This could reflect a change in the quantity of an economic resource. It is also defined by its behavior in relation to the economic resource (see `Action`)
"""
type EconomicEvent {
  id: ID!
  action: Action
  inputOf: Process
  outputOf: Process
  provider: Agent
  receiver: Agent
  inScopeOf: Agent #TODO how to loosen this up to be more than Agent? (mostly it is Agents)
  affects: EconomicResource
  resourceClassifiedAs: [ResourceClassification]
  resourceConformsTo: ResourceSpecification
  affectedQuantity: QuantityValue
  observedTime: TemporalEntity #TODO: define what this actually can be
  # requestDistribution: Boolean
  note: String
  fulfills: [Fulfillment]
  # validations: [Validation]
  # isValidated: Boolean
  # userIsAuthorizedToUpdate: Boolean
  # userIsAuthorizedToDelete: Boolean
}

"""
A resource which is useful to people or the ecosystem.
"""
type EconomicResource {
  id: ID!
  url: String!
  resourceClassifiedAs: [String]
  resourceConformsTo: ResourceSpecification
  trackingIdentifier: String
  image: String
  currentQuantity: QuantityValue
  note: String
  category: String #TODO: check this
  currentLocation: String
  createdDate: String #TODO: put these everywhere?
  transfers: [Transfer]
  # resourceContacts: [Agent]
  # owners: [Agent]  TODO: define agent-resource relationships, if we do need them
}

"""
An activity that assigns the rights and responsibilities for an economic resource from one agent to another.
"""
type Transfer { #TODO this whole model is under review
  id: ID!
  name: String!
  # under: ExchangeAgreement TODO need to finish this definition
  plannedTime: TemporalEntity #TODO: define what this actually can be - or if it should even be here
  note: String
  economicEvents: [EconomicEvent]
  giveEconomicEvent: EconomicEvent
  takeEconomicEvent: EconomicEvent
  transferCommitments: [Commitment]
  giveCommitment: Commitment
  takeCommitment: Commitment
  involvedAgents: [Agent]
}

"""
An activity that changes inputs into outputs.  It could transform or transport economic resource(s).
"""
type Process {
  id: ID!
  name: String!
  inScopeOf: Agent
  plannedTime: TemporalEntity
  started: Boolean
  finished: Boolean
  basedOn: RecipeProcess
  note: String
  deletable: Boolean
  inputs(action: Action): [EconomicEvent]
  outputs(action: Action): [EconomicEvent]
  unplannedEconomicEvents(action: Action): [EconomicEvent]
  committedInputs(action: Action): [Commitment]
  committedOutputs(action: Action): [Commitment]
  nextProcesses: [Process]
  previousProcesses: [Process]
  workingAgents: [Agent]
  plan: Plan
  # userIsAuthorizedToUpdate: Boolean
  # userIsAuthorizedToDelete: Boolean
}

#type Validation {
#  id: ID!
#  validationDate: DateTime
# note: String
# validatedBy: Agent
#  economicEvent: EconomicEvent
#}
