##
#
# Main query entrypoint
#
#
##

type Query {

  # Agent module
  myAgent: Agent
  agent(id: String): Agent
  allAgents: [Agent]

  organization(id: String): Organization
  allOrganizations: [Organization]

  person(id: String): Person
  allPeople: [Person]

  agentRelationship(id: String): AgentRelationship
  allAgentRelationships: [AgentRelationship]
  agentRelationshipRole(id: String): AgentRelationshipRole
  allAgentRelationshipRoles: [AgentRelationshipRole]

  # Observation layer
  economicEvent(id: String): EconomicEvent
  allEconomicEvents: [EconomicEvent]
  filteredEconomicEvents(
    providerId: String,
    receiverId: String,
    resourceClassifiedAs: String,
    action: Action,
    startDate: String,
    endDate: String
  ): [EconomicEvent]

  fulfillment(id: String): Fulfillment
  allFulfillments: [Fulfillment]

  economicResource(id: String): EconomicResource
  allEconomicResources: [EconomicResource]

  #validation(id: String): Validation
  #allValidations: [Validation]

  process(id: String): Process
  allProcesses: [Process]

  transfer(id: String): Transfer
  allTransfers: [Transfer]

  # Planning layer
  allRecipes: [ResourceClassification]

  commitment(id: String): Commitment
  allCommitments: [Commitment]

  satisfaction(id: String): Satisfaction
  allSatisfactions: [Satisfaction]

  plan(id: String): Plan
  allPlans: [Plan]

  exchangeAgreement(id: String): ExchangeAgreement
  allExchangeAgreements: [ExchangeAgreement]

  # Knowledge layer
  resourceClassification(id: String): ResourceClassification
  allResourceClassifications: [ResourceClassification]
  resourceClassificationsByProcessCategory(category: EconomicResourceProcessCategory): [ResourceClassification]
  resourceClassificationsByAction(action: Action): [ResourceClassification]
  resourceClassificationsByFacetValues(facetValues: String): [ResourceClassification]

  agentResourceClassification(id: String): AgentResourceClassification
  allAgentResourceClassifications: [AgentResourceClassification]

  processClassification(id: String): ProcessClassification
  allProcessClassifications: [ProcessClassification]

  organizationClassification(id: String): OrganizationClassification
  allOrganizationClassifications: [OrganizationClassification]

  resourceSpecification(id: String): ResourceSpecification
  allResourceSpecifications: [ResourceSpecification]

  recipeProcess(id: String): RecipeProcess
  allRecipeProcesses: [RecipeProcess]

  recipeFlow(id: String): RecipeFlow
  allRecipeFlows: [RecipeFlow]

  action(id: String): Action
  allActions: [Action]

  #facet(id: String): Facet
  #allFacets: [Facet]

  # System config layer
  unit(id: String): Unit
  allUnits: [Unit]

  quantityValue(id: String): QuantityValue

  location(id: String): Location #TODO: ??
  allLocations: [Location] #TODO: ??

}
