##
#
# Utility structs
#
# These are common data structures used throughout the API
#
#
##

"""
The `DateTime` scalar type represents a DateTime
value as specified by
[iso8601](https://en.wikipedia.org/wiki/ISO_8601).
"""
scalar DateTime

"""
Defines a unit of measurement, along with its display symbol.
"""
type Unit {
  id: ID!
  name: String!
  symbol: String!
}

"""
Semantic meaning for measurements: binds a quantity to its measurement unit.
"""
type QuantityValue {
  quantity: Float
  unit: Unit
}

"""
A physical location (not defined by ValueFlows)
"""
type Location { #TODO: ??
  id: ID!
  name: String!
  address: String!
  latitude: Float
  longitude: Float
  note: String
  ### inverse relationships and queries
  resources: [EconomicResource]
  agents: [Agent]
}
