##
#
# Utility structs
#
# These are common data structures used throughout the API
#
# @package  vf-graphql
# @author   pospi <pospi@spadgos.com>
# @since    2019-02-11
#
##

"""
The `DateTime` scalar type represents a DateTime
value as specified by
[iso8601](https://en.wikipedia.org/wiki/ISO_8601).
"""
scalar DateTime

"""
Defines a unit of measurement, along with its display symbol.
"""
type Unit {
  id: ID!
  name: String!
  symbol: String!
}

"""
Semantic meaning for measurements: binds a quantity to its measurement unit.
"""
type QuantityValue {
  quantity: Float
  unit: Unit
}

"""
A physical location
"""
type Place {
  id: ID!
  name: String!
  address: String!
  latitude: Float
  longitude: Float
  note: String
  placeResources: [EconomicResource]
  placeAgents: [Agent]
}
