##
#
# Utility structs
#
# These are common data structures used throughout the API
#
#
##

"""
A type which allows any arbitrary value to be set
"""
scalar AnyType

"""
The `URL` type simply declares a reference to an external web URL.
"""
scalar URL

"""
The `DateTime` scalar type represents a DateTime value as specified by
[ISO 8601](https://en.wikipedia.org/wiki/ISO_8601).
"""
scalar DateTime

"""
The `DateInterval` scalar type represents an interval between two `DateTime` values
as specified by [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Durations).
"""
scalar DateInterval

"""
Defines a unit of measurement, along with its display symbol.
See http://qudt.org/1.1/vocab/unit
"""
type Unit {
  id: ID!
  name: String!
  symbol: String!
}

"""
Semantic meaning for measurements: binds a quantity to its measurement unit.
"""
type QuantityValue {
  numericValue: Float
  unit: Unit
}

"""
Mutation input structure for defining measurements. Should be nulled if not present, rather than empty.
"""
input IQuantityValue {
  unit: ID!,
  numericValue: Float!
}

"""
A physical location (not defined by ValueFlows)
"""
type Location { #TODO: ??
  id: ID!
  name: String!
  address: String!
  latitude: Float
  longitude: Float
  note: String
  ### inverse relationships and queries
  resources: [EconomicResource]
  agents: [Agent]
}
