##
#
# Agent module
#
# All functionality related to the definition of autonomous agents
# (people, organizations, groups) and their relationships.
#
# @package  vf-graphql
# @since    2019-02-11
#
##

"""
A person or group or organization with economic agency.
"""
interface Agent {
  id: ID!

  "An informal or formal textual identifier for an agent. Does not imply uniqueness."
  name: String!

  "The uri to an image relevant to the agent, such as a logo, avatar, photo, etc."
  image: URI

  "The main place an agent is located, often an address where activities occur and mail can be sent. This is usually a mappable geographic location.  It also could be a website address, as in the case of agents who have no physical location."
  primaryLocation: ID

  "A textual description or comment."
  note: String

  ##############################################################################
  # inverse relationships and queries

  relationships(roleId: ID): [AgentRelationship!] # :TODO: category filtering
  relationshipsAsSubject(roleId: ID): [AgentRelationship!] # :TODO: category filtering
  relationshipsAsObject(roleId: ID): [AgentRelationship!] # :TODO: category filtering

  roles: [AgentRelationshipRole!]
}

"""
A natural person.
"""
type Person implements Agent {
  id: ID!

  "The name that this agent will be referred to by."
  name: String!

  "The uri to an image relevant to the agent, such as a logo, avatar, photo, etc."
  image: URI

  "The main place an agent is located, often an address where activities occur and mail can be sent. This is usually a mappable geographic location.  It also could be a website address, as in the case of agents who have no physical location."
  primaryLocation: ID

  "A textual description or comment."
  note: String

  ##############################################################################
  # inverse relationships and queries

  relationships(roleId: ID): [AgentRelationship!] # :TODO: category filtering
  relationshipsAsSubject(roleId: ID): [AgentRelationship!] # :TODO: category filtering
  relationshipsAsObject(roleId: ID): [AgentRelationship!] # :TODO: category filtering

  roles: [AgentRelationshipRole!]
}

"""
A formal or informal group, or legal organization.
"""
type Organization implements Agent {
  id: ID!

  # :TODO: define how people can create further typing of Organization
  # type: OrganizationClassification

  "The name that this agent will be referred to by."
  name: String!

  "The uri to an image relevant to the agent, such as a logo, avatar, photo, etc."
  image: URI

  "The main place an agent is located, often an address where activities occur and mail can be sent. This is usually a mappable geographic location.  It also could be a website address, as in the case of agents who have no physical location."
  primaryLocation: ID

  "A textual description or comment."
  note: String

  ##############################################################################
  # inverse relationships and queries

  relationships(roleId: ID): [AgentRelationship!] # :TODO: category filtering
  relationshipsAsSubject(roleId: ID): [AgentRelationship!] # :TODO: category filtering
  relationshipsAsObject(roleId: ID): [AgentRelationship!] # :TODO: category filtering

  roles: [AgentRelationshipRole!]
}

# Relationships between agents

"""
The role of an economic relationship that exists between 2 agents, such as member, trading partner.
"""
type AgentRelationship {
  id: ID!

  "The subject of a relationship between 2 agents.  For example, if Mary is a member of a group, then Mary is the subject."
  subject: Agent!

  "The object of a relationship between 2 agents.  For example, if Mary is a member of a group, then the group is the object."
  object: Agent!

  "A kind of relationship that exists between 2 agents."
  relationship: AgentRelationshipRole!

  "Grouping around something to create a boundary or context, used for documenting, accounting, planning."
  inScopeOf: [AnyType!]

  "A textual description or comment."
  note: String
}

"""
A relationship role defining the kind of association one agent can have with another.
"""
type AgentRelationshipRole {
  id: ID!

  "The human readable name of the role, from the subject to the object."
  roleLabel: String!

  "The human readable name of the role, from the object to the subject."
  inverseRoleLabel: String

  "A textual description or comment."
  note: String

  # :TODO: https://github.com/valueflows/valueflows/issues/494
}

# :TODO: how do we want to do this concept?
# """
# Generalized behaviors for agent relationship roles
# """
# enum AgentRelationshipCategory {
#   LEGALPARTNER
#   MEMBER
#   PART
#   PEER
#   TRADINGPARTNER
# }





# interface AgentParams {
#   name: String
#   image: URI
#   primaryLocation: String
#   note: String
# }

input AgentCreateParams { # implements AgentParams
  "An informal or formal textual identifier for an agent. Does not imply uniqueness."
  name: String!

  "The uri to an image relevant to the agent, such as a logo, avatar, photo, etc."
  image: URI

  "The main place an agent is located, often an address where activities occur and mail can be sent. This is usually a mappable geographic location.  It also could be a website address, as in the case of agents who have no physical location."
  primaryLocation: ID

  "A textual description or comment."
  note: String
}

input AgentUpdateParams { # implements UpdateParams & AgentParams
  id: ID!

  "An informal or formal textual identifier for an agent. Does not imply uniqueness."
  name: Strin

  "The uri to an image relevant to the agent, such as a logo, avatar, photo, etc."
  image: URI

  "The main place an agent is located, often an address where activities occur and mail can be sent. This is usually a mappable geographic location.  It also could be a website address, as in the case of agents who have no physical location."
  primaryLocation: ID

  "A textual description or comment."
  note: String
}

type PersonResponse {
  agent: Person!
}

type OrganizationResponse {
  agent: Organization!
}


# interface AgentRelationshipParams {
#   subject: ID
#   object: ID
#   relationship: ID
#   note: String
# }

input AgentRelationshipCreateParams { # implements AgentRelationshipParams
  "The subject of a relationship between 2 agents.  For example, if Mary is a member of a group, then Mary is the subject."
  subject: ID! # Agent

  "The object of a relationship between 2 agents.  For example, if Mary is a member of a group, then the group is the object."
  object: ID! # Agent

  "The role of an economic relationship that exists between 2 agents, such as member, trading partner."
  relationship: ID! # AgentRelationshipRole

  "A textual description or comment."
  note: String
}

input AgentRelationshipUpdateParams { # implements UpdateParams & AgentRelationshipParams
  id: ID!

  "The subject of a relationship between 2 agents.  For example, if Mary is a member of a group, then Mary is the subject."
  subject: ID

  "The object of a relationship between 2 agents.  For example, if Mary is a member of a group, then the group is the object."
  object: ID

  "The role of an economic relationship that exists between 2 agents, such as member, trading partner."
  relationship: ID

  "A textual description or comment."
  note: String
}

type AgentRelationshipResponse {
  agentRelationship: AgentRelationship!
}


# interface AgentRelationshipRoleParams {
#   roleLabel: String
#   inverseRoleLabel: String
#   note: String
# }

input AgentRelationshipRoleCreateParams { # implements AgentRelationshipRoleParams
  "The human readable name of the role, inverse from the object to the subject. For example, 'is member of'."
  roleLabel: String!

  "The human readable name of the role, inverse from the object to the subject. For example, 'has member'."
  inverseRoleLabel: String

  "A textual description or comment."
  note: String
}

input AgentRelationshipRoleUpdateParams { # implements UpdateParams & AgentRelationshipRoleParams
  id: ID!

  "The human readable name of the role, inverse from the object to the subject. For example, 'is member of'."
  roleLabel: String

  "The human readable name of the role, inverse from the object to the subject. For example, 'has member'."
  inverseRoleLabel: String

  "A textual description or comment."
  note: String
}

type AgentRelationshipRoleResponse {
  agentRelationshipRole: AgentRelationshipRole
}

type Query {
  "Loads details of the currently authenticated REA agent"
  myAgent: Agent

  "Find an agent (person or organization) by their ID"
  agent(id: ID): Agent
  "Loads all agents publicly registered within this collaboration space"
  allAgents(start: ID, limit: Int): [Agent!]

  "Find an organization (group) agent by its ID"
  organization(id: ID): Organization
  "Loads all organizations publicly registered within this collaboration space"
  allOrganizations(start: ID, limit: Int): [Organization!]

  "Find a person by their ID"
  person(id: ID): Person
  "Loads all people who have publicly registered with this collaboration space."
  allPeople(start: ID, limit: Int): [Person!]

  "Retrieve details of an agent relationship by its ID"
  agentRelationship(id: ID): AgentRelationship
  "Retrieve details of all the relationships between all agents registered in this collaboration space"
  allAgentRelationships(start: ID, limit: Int): [AgentRelationship!]
  "Retrieve details of an agent relationship role by its ID"
  agentRelationshipRole(id: ID): AgentRelationshipRole
  "Retrieve all possible kinds of associations that agents may have with one another in this collaboration space"
  allAgentRelationshipRoles(start: ID, limit: Int): [AgentRelationshipRole!]
}

type Mutation {
  "Registers a new (human) person with the collaboration space"
  createPerson(person: AgentCreateParams!): PersonResponse
  "Update profile details"
  updatePerson(person: AgentUpdateParams!): PersonResponse
  "Erase record of a person and thus remove them from the collaboration space"
  deletePerson(id: String!): Boolean

  "Registers a new organization (group agent) with the collaboration space"
  createOrganization(organization: AgentCreateParams!): OrganizationResponse
  "Update organization profile details"
  updateOrganization(organization: AgentUpdateParams!): OrganizationResponse
  "Erase record of an organization and thus remove it from the collaboration space"
  deleteOrganization(id: String!): Boolean

  createAgentRelationship(relationship: AgentRelationshipCreateParams!): AgentRelationshipResponse
  updateAgentRelationship(relationship: AgentRelationshipUpdateParams!): AgentRelationshipResponse
  deleteAgentRelationship(id: String!): Boolean

  createAgentRelationshipRole(agentRelationshipRole: AgentRelationshipRoleCreateParams): AgentRelationshipRoleResponse
  updateAgentRelationshipRole(agentRelationshipRole: AgentRelationshipRoleUpdateParams): AgentRelationshipRoleResponse
  deleteAgentRelationshipRole(id: String!): Boolean
}
