##
#
# Appreciation module
#
# Allows linking EconomicEvents to indicate that some contribution was given in loose appreciation for another.
#
# @depends  observation.gql
# @package  vf-graphql
# @since    2019-02-11
#
##

"""
A way to tie an economic event that is given in loose fulfilment for another economic event, without commitments or expectations.
Supports the gift economy.
"""
type Appreciation {
  id: ID!

  "The `EconomicEvent` this appreciation has been given in acknowledgement of"
  appreciationOf: EconomicEvent!

  "The `EconomicEvent` provided as a gift in this appreciation"
  appreciationWith: EconomicEvent!

  "A textual description or comment."
  note: String
}




# interface AppreciationParams {
#   appreciationOf: ID
#   appreciationWith: ID
#   note: String
# }

input AppreciationCreateParams {
  appreciationOf: ID # EconomicEvent
  appreciationWith: ID # EconomicEvent
  note: String
}

input AppreciationUpdateParams {
  id: ID!
  appreciationOf: ID # EconomicEvent
  appreciationWith: ID # EconomicEvent
  note: String
}

type AppreciationResponse {
  appreciation: Appreciation
}

type Mutation {
  createAppreciation(appreciation: AppreciationCreateParams!): AppreciationResponse
  updateAppreciation(appreciation: AppreciationUpdateParams!): AppreciationResponse
  deleteAppreciation(id: String!): Boolean
}
