##
#
# Appreciation module
#
# Allows linking EconomicEvents to indicate that some contribution was given in loose appreciation for another.
#
# @depends  observation.gql
# @package  vf-graphql
# @since    2019-02-11
#
##

"""
A way to tie an economic event that is given in loose fulfilment for another economic event, without commitments or expectations.
Supports the gift economy.
"""
type Appreciation {
  id: ID!

  "The economic event this appreciation has been given in acknowledgement of."
  appreciationOf: EconomicEvent!

  "The economic event provided as a gift in this appreciation."
  appreciationWith: EconomicEvent!

  "A textual description or comment."
  note: String
}



input AppreciationCreateParams {
  "(`EconomicEvent`) The economic event this appreciation has been given in acknowledgement of."
  appreciationOf: ID!

  "(`EconomicEvent`) The economic event provided as a gift in this appreciation."
  appreciationWith: ID!

  "A textual description or comment."
  note: String
}

input AppreciationUpdateParams {
  id: ID!

  "(`EconomicEvent`) The economic event this appreciation has been given in acknowledgement of."
  appreciationOf: ID

  "(`EconomicEvent`) The economic event provided as a gift in this appreciation."
  appreciationWith: ID

  "A textual description or comment."
  note: String
}

type AppreciationResponse {
  appreciation: Appreciation
}



type Mutation {
  createAppreciation(appreciation: AppreciationCreateParams!): AppreciationResponse
  updateAppreciation(appreciation: AppreciationUpdateParams!): AppreciationResponse
  deleteAppreciation(id: ID!): Boolean
}
