##
#
# Observation layer
#
# Record of what actually happened affecting the economic ecosystem.
#
#
##

union ProductionFlowItem = Process | EconomicResource

"""
An observed economic flow, as opposed to a flow planned to happen in the future. This could reflect a change in the quantity of an economic resource. It is also defined by its behavior in relation to the economic resource (see `Action`)
"""
type EconomicEvent {
  id: ID!

  "Relates a process input or output to a verb, such as consume, produce, work, improve, etc."
  action: Action!

  "Defines the process to which this event is an input."
  inputOf: Process

  "Defines the process for which this event is an output."
  outputOf: Process

  "The economic agent from whom the actual economic event is initiated."
  provider: Agent

  "The economic agent whom the actual economic event is for."
  receiver: Agent

  "Economic resource involved in the economic event."
  resourceInventoriedAs: EconomicResource

  "Additional economic resource on the economic event when needed by the receiver. Used when a transfer or move, or sometimes other actions, requires explicitly identifying an economic resource on the receiving side."
  toResourceInventoriedAs: EconomicResource

  "References a concept in a common taxonomy or other classification scheme for purposes of categorization or grouping."
  resourceClassifiedAs: [URI!]

  "The primary resource specification or definition of an existing or potential economic resource. A resource will have only one, as this specifies exactly what the resource is."
  resourceConformsTo: ResourceSpecification

  "The amount and unit of the economic resource counted or inventoried."
  resourceQuantity: QuantityValue

  "The amount and unit of the work or use or citation effort-based action. This is often a time duration, but also could be cycle counts or other measures of effort or usefulness."
  effortQuantity: QuantityValue

  "The beginning of the economic event."
  hasBeginning: DateTime

  "The end of the economic event."
  hasEnd: DateTime

  "The date/time at which the economic event occurred."
  hasPointInTime: DateTime

  "The economic event occurred prior to this date/time."
  before: DateTime

  "The economic event occurred after this date/time."
  after: DateTime

  "The place where an economic event occurs.  Usually mappable."
  atLocation: SpatialThing

  "A textual description or comment."
  note: String

  "Grouping around something to create a boundary or context, used for documenting, accounting, planning."
  inScopeOf: [AnyType!]

  "Reference to an agreement between agents which specifies the rules or policies or calculations which govern this economic event."
  agreedIn: AnyAgreement

  "This economic event occurs as part of this agreement."
  realizationOf: Agreement

  "References another economic event that implied this economic event, often based on a prior agreement."
  triggeredBy: EconomicEvent

  # requestDistribution: Boolean

  ##############################################################################
  # inverse relationships and queries

  "The commitment which is completely or partially fulfilled by an economic event."
  fulfills: [Fulfillment!]

  "An intent satisfied fully or partially by an economic event or commitment."
  satisfies: [Satisfaction!]

  appreciationOf: [EconomicEvent!]
  appreciatedBy: [EconomicEvent!]

  track: [ProductionFlowItem!]
  trace: [ProductionFlowItem!]

  # validations: [Validation!]
  # isValidated: Boolean

  "The economic event can be safely deleted, has no dependent information."
  deletable: Boolean
}

"""
A resource which is useful to people or the ecosystem.
"""
type EconomicResource {
  id: ID!

  "References one or more concepts in a common taxonomy or other classification scheme for purposes of categorization or grouping."
  classifiedAs: [URI!]

  "The primary resource specification or definition of an existing or potential economic resource. A resource will have only one, as this specifies exactly what the resource is."
  conformsTo: ResourceSpecification!

  "Sometimes called serial number, used when each item must have a traceable identifier (like a computer). Could also be used for other unique tracking identifiers needed for resources."
  trackingIdentifier: String

  "Lot or batch of an economic resource, used to track forward or backwards to all occurrences of resources of that lot. Note more than one resource can be of the same lot."
  lot: ProductBatch

  "The uri to an image relevant to the resource, such as a photo, diagram, etc."
  image: URI

  "The current amount and unit of the economic resource for which the agent has primary rights and responsibilities, sometimes thought of as ownership. This can be either stored or derived from economic events affecting the resource."
  accountingQuantity: QuantityValue

  "The current amount and unit of the economic resource which is under direct control of the agent.  It may be more or less than the accounting quantity. This can be either stored or derived from economic events affecting the resource."
  onhandQuantity: QuantityValue

  "A textual description or comment."
  note: String

  "The unit used for use or work or cite actions for this resource."
  unitOfEffort: Unit

  "The last stage the economic resource went through. Can be derived from the most recent process with this resource as an output."
  stage: ProcessSpecification

  "The state of the desired economic resource (pass or fail), after coming out of a test or review process. Can be derived from the last event if a pass or fail event."
  state: Action

  "Used when a stock economic resource contains items also defined as economic resources."
  containedIn

  "The current place an economic resource is located. Could be at any level of granularity, from a town to an address to a warehouse location. Usually mappable."
  currentLocation: SpatialThing

  ##############################################################################
  # inverse relationships and queries

  "Used when a stock economic resource contains units also defined as economic resources."
  contains: [EconomicResource!]

  trace: [EconomicEvent!]
  track: [EconomicEvent!]

  # resourceContacts: [Agent!]
  # owners: [Agent!]  TODO: define agent-resource relationships, if we do need them
}

"""
A lot or batch, defining a resource produced at the same time in the same way.
From DataFoodConsortium vocabulary https://datafoodconsortium.gitbook.io/dfc-standard-documentation/.
"""
type ProductBatch {
  id: ID!

  "The standard unique identifier of the batch."
  batchNumber: String!

  "Expiration date of the batch, commonly used for food."
  expiryDate: DateTime

  "Date the batch was produced.  Can be derived from the economic event of production."
  productionDate: DateTime
}

"""
An activity that changes inputs into outputs.  It could transform or transport economic resource(s).
"""
type Process {
  id: ID!

  "An informal or formal textual identifier for an item. Does not imply uniqueness."
  name: String!

  "The planned beginning of the process."
  hasBeginning: DateTime

  "The planned end of the process."
  hasEnd: DateTime

  "The due date/time of the process."
  before: DateTime

  "The process can start after this date/time."
  after: DateTime

  "The process is complete or not.  This is irrespective of if the original goal has been met, and indicates that no more will be done."
  finished: Boolean

  "The definition or specification for a process."
  basedOn: ProcessSpecification

  "References one or more concepts in a common taxonomy or other classification scheme for purposes of categorization or grouping."
  classifiedAs: [URI!]

  "A textual description or comment."
  note: String

  "Grouping around something to create a boundary or context, used for documenting, accounting, planning."
  inScopeOf: [AnyType!]

  "The process with its inputs and outputs is part of the plan."
  plannedWithin: Plan

  ##############################################################################
  # inverse relationships and queries

  inputs(action: ID): [EconomicEvent!]
  outputs(action: ID): [EconomicEvent!]
  unplannedEconomicEvents(action: ID): [EconomicEvent!]

  committedInputs(action: ID): [Commitment!]
  committedOutputs(action: ID): [Commitment!]

  intendedInputs(action: ID): [Intent!]
  intendedOutputs(action: ID): [Intent!]

  nextProcesses: [Process!]
  previousProcesses: [Process!]

  workingAgents: [Agent!]

  trace: [EconomicEvent!]
  track: [EconomicEvent!]

  "The process can be safely deleted, has no dependent information."
  deletable: Boolean
}

"""
A way to tie an economic event that is given in loose fulfilment for another economic event, without commitments or expectations. Supports the gift economy.
"""
type Appreciation {
  id: ID!

  "The `EconomicEvent` this appreciation has been given in acknowledgement of"
  appreciationOf: EconomicEvent!

  "The `EconomicEvent` provided as a gift in this appreciation"
  appreciationWith: EconomicEvent!

  "A textual description or comment."
  note: String
}
