##
#
# Plan module
#
# Allows for grouping processes into related groups of work with defined deliverables.
#
# @depends  scenario.gql
# @package  vf-graphql
# @since    2019-02-11
#
##

"""
A logical collection of processes that constitute a body of planned work with defined deliverable(s).
"""
type Plan {
  id: ID!

  "An informal or formal textual identifier for a plan. Does not imply uniqueness."
  name: String

  "The time the plan was made."
  created: DateTime

  "The time the plan is expected to be complete."
  due: DateTime

  "A textual description or comment."
  note: String

  "This plan refines a scenario, making it operational."
  refinementOf: Scenario

  ##############################################################################
  # inverse relationships and queries

  "Grouping around something to create a boundary or context, used for documenting, accounting, planning."
  inScopeOf: [AnyType!]

  "The plan is able to be deleted or not."
  deletable: Boolean
}



input PlanCreateParams {
  "An informal or formal textual identifier for a plan. Does not imply uniqueness."
  name: String!

  "The time the plan was made."
  created: DateTime

  "The time the plan is expected to be complete."
  due: DateTime

  "A textual description or comment."
  note: String

  "(`Scenario`) This plan refines a scenario, making it operational."
  refinementOf: ID
}

input PlanUpdateParams {
  id: ID!

  "An informal or formal textual identifier for a plan. Does not imply uniqueness."
  name: String

  "The time the plan was made."
  created: DateTime

  "The time the plan is expected to be complete."
  due: DateTime

  "A textual description or comment."
  note: String

  "(`Scenario`) This plan refines a scenario, making it operational."
  refinementOf: ID
}

type PlanResponse {
  plan: Plan
}



type Query {
  plan(id: ID): Plan
  plans(start: ID, limit: Int): [Plan!]
}

type Mutation {
  createPlan(plan: PlanCreateParams!): PlanResponse
  # :TODO:
  # createPlanFromRecipe(): PlanResponse
  updatePlan(plan: PlanUpdateParams!): PlanResponse
  deletePlan(id: String!): Boolean
}
