##
#
# Utility structs
#
# These are common data structures used throughout the API
#
#
##

"""
A type which allows any arbitrary value to be set
"""
scalar AnyType

"""
The `URI` type simply declares a reference to an external web URL, Holochain entry or other resource.
"""
scalar URI

"""
The `DateTime` scalar type represents a DateTime value as specified by
[ISO 8601](https://en.wikipedia.org/wiki/ISO_8601).
"""
scalar DateTime

"""
Defines the unit of time measured in a temporal `Duration`.
"""
enum TimeUnit {
  year, month, week, day, hour, minute, second
}

"""
A `Duration` represents an interval between two `DateTime` values.
"""
type Duration {
  numericDuration: Float!
  unitType: TimeUnit!
}

"""
Defines a unit of measurement, along with its display symbol.
From OM2 vocabulary.
"""
type Unit {
  id: ID!
  label: String!
  symbol: String!
}

"""
Semantic meaning for measurements: binds a quantity to its measurement unit.
See http://www.qudt.org/pages/QUDToverviewPage.html
"""
type Measure {
  hasNumericalValue: Float! # we now allow Decimal, Double, Float, or Integer - let's discuss!
  hasUnit: Unit
}

"""
Mutation input structure for defining measurements. Should be nulled if not present, rather than empty.
"""
input IMeasure {
  hasNumericalValue: Float! # we now allow Decimal, Double, Float, or Integer - let's discuss!
  hasUnit: Unit
}

"""
Mutation input structure for defining time durations.
"""
input IDuration {
  numericDuration: Decimal!
  unitType: TimeUnit!
}

"""
A physical mappable location.
"""
type SpatialThing {
  id: ID!
  name: String!
  mappableAddress: String
  lat: Float
  long: Float
  alt: Float

  "A textual description or comment."
  note: String

  ##############################################################################
  # inverse relationships and queries

  economicResources: [EconomicResource!]
  agents: [Agent!]
  economicEvents: [EconomicEvent!]
  commitments: [Commitment!]
  intents: [Intent!]
}
